[toolchain]
anchor_version = "0.29.0"  
solana_version = "1.17.28"  

[features]
seeds = false
skip-lint = false

[programs.localnet]
soundwork-bid = "7Kehs8uKmqUq62s9aXTtU348HagoeR8RLZiUY5XMsct3"
soundwork-create = "DEmW5Gz7c4PzaMXayyYjWkkDfiXeEQoLysSdgCuepw5b"
soundwork-list = "Cdn2CtPiYR9Lar4JnzhQbY3Gy4s6xYVjQLy3NBvZAN6k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/soundwork-create.ts" 
list = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/soundwork-list.ts"