[toolchain]
anchor_version = "0.30.1"  
# solana_version = "1.18.11" system version. do not uncomment  
# solana_version = "1.17.28"  

[features]
seeds = false
skip-lint = false

[programs.localnet]
soundwork-bid = "4mFDYND4AVREYEJXCPhjq1LnbjELHHebJqG3NZechA7X"
soundwork-create = "FegMMZtuFu8ZUTjdkt2yRR1TmGEAFZbjpDJWpQ4ueqyG"
soundwork-list = "EA4ptgF3TYjDBGYJApAoZoyCbCYw6P5mGU5noCe1Z97"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/soundwork-create.ts" 
list = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/soundwork-list.ts"
bid = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/soundwork-bid.ts"
